#!/usr/bin/env bash
echo "# $0"

# prefix all stderr with '#':
exec 2> >(sed 's/^/#error: /')

# stop if a command is missing
err=0
for cmd in vcgencmd ; do
    command -v $cmd >/dev/null && continue || { echo "# $cmd command not found."; err=1; }
done
test $err -eq 1 && exit $FAILURE


VOLTAGE=$(vcgencmd measure_volts | sed 's/[^0-9.V]//g')

TEMPURATURE=$(vcgencmd measure_temp | sed 's/[^0-9.]//g')

if vcgencmd commands | grep -q 'get_throttled' ; then
    THROTTLED=$(vcgencmd get_throttled | cut -d= -f2)
    THROTTLED_UNDERVOLTAGE_DETECTED=$((    $THROTTLED&0x1  ))
    THROTTLED_ARM_FREQ_CAPPED=$((         ($THROTTLED&0x2) >> 1 ))
    THROTTLED_CURRENTLY_THROTTLED=$((     ($THROTTLED&0x4) >> 2 ))
    THROTTLED_SOFT_TEMP_LIMIT_ACTIVE=$((  ($THROTTLED&0x8) >> 3 ))
    THROTTLED_UNDERVOLTAGE_OCCURED=$((    ($THROTTLED&0x1000) >> 16))
    THROTTLED_ARM_FREQ_CAPPED_OCCURED=$(( ($THROTTLED&0x2000) >> 17))
    THROTTLED_THROTTLING_OCCURED=$((      ($THROTTLED&0x4000) >> 18))
    THROTTLED_SOFT_TEMP_LIMIT_OCCURED=$(( ($THROTTLED&0x8000) >> 19))
fi

dmesg | grep -qi 'under-voltage' \
&& DMESG_UNDERVOLTAGE=1 \
|| DMESG_UNDERVOLTAGE=0 \

#vcgencmd get_config int
cat <<EOM
POWER_VOLTAGE=$VOLTAGE
POWER_TEMPURATURE=$TEMPURATURE
POWER_DMESG_UNDERVOLTAGE=$DMESG_UNDERVOLTAGE
EOM

if test -n "$THROTTLED"; then
cat <<EOM
POWER_THROTTLED=$THROTTLED
# parsed bit values:
POWER_THROTTLED_UNDERVOLTAGE_DETECTED=$THROTTLED_UNDERVOLTAGE_DETECTED
POWER_THROTTLED_ARM_FREQ_CAPPED=$THROTTLED_ARM_FREQ_CAPPED
POWER_THROTTLED_CURRENTLY_THROTTLED=$THROTTLED_CURRENTLY_THROTTLED
POWER_THROTTLED_SOFT_TEMP_LIMIT_ACTIVE=$THROTTLED_SOFT_TEMP_LIMIT_ACTIVE
POWER_THROTTLED_UNDERVOLTAGE_OCCURED=$THROTTLED_UNDERVOLTAGE_OCCURED
POWER_THROTTLED_ARM_FREQ_CAPPED_OCCURED=$THROTTLED_ARM_FREQ_CAPPED_OCCURED
POWER_THROTTLED_THROTTLING_OCCURED=$THROTTLED_THROTTLING_OCCURED
POWER_THROTTLED_SOFT_TEMP_LIMIT_OCCURED=$THROTTLED_SOFT_TEMP_LIMIT_OCCURED
EOM
fi

RESULT=$SUCCESS

# DO SOME TESTS TO CHECK VALUES ARE REASONABLE BEFORE EXITING WITH SUCCESS OR FAILURE STATUS